title: "My Recipe Book"
description: "A quiet little place for recipes."
url: ""
baseurl: ""

collections:
  recipes:
    output: true
    permalink: /recipes/:name/

defaults:
  - scope:
      path: ""
      type: recipes
    values:
      layout: recipe
      section: recipes
